_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.5
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": darwin-arm64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activations:
    value:
        - relu
        - softmax
architecture:
    value: MLP
batch_size:
    value: 32
dataset:
    value: Iris
epochs:
    value: 50
layers:
    value:
        - 4
        - 16
        - 3
learning_rate:
    value: 0.001
